FROM python:3.9-slim

WORKDIR /app
ENV PIP_ROOT_USER_ACTION=ignore

RUN apt-get update && apt-get install -y gnupg2

COPY python-requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

ARG PASSPHRASE
RUN echo $PASSPHRASE | gpg --quiet --batch --yes --passphrase-fd 0 --output=.env .env.gpg

EXPOSE 4200

RUN chmod +x /app/run-server.sh

CMD ["/app/run-server.sh"]
